version: '3.8'

services:
  apigetway:
    build:
      context: .
      dockerfile: ./apps/apigetway/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - order_service
      - product_service
      - user_service
    env_file:
      - .env

  order_service:
    build:
      context: .
      dockerfile: ./apps/order_service/Dockerfile
    ports:
      - '5002:5002'
    depends_on:
      - db
      - product_service
    env_file:
      - .env

  product_service:
    build:
      context: .
      dockerfile: ./apps/product_service/Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
    env_file:
      - .env

  user_service:
    build:
      context: .
      dockerfile: ./apps/user_service/Dockerfile
    ports:
      - '5001:5001'
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
