// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: proto/user-service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user_service";

export interface Empty {
}

export interface FindOneUserDto {
  id: string;
}

export interface UpdateUserDto {
  id: string;
}

export interface CreateUserDto {
  username: string;
  password: string;
  fullName: string;
}

export interface SignInDto {
  username: string;
  password: string;
}

export interface User {
  id: string;
  username: string;
  password: string;
  fullName: string;
}

export interface Users {
  users: User[];
}

export interface SignInResponse {
  user: User | undefined;
  accessToken: string;
  expiresIn: string;
}

export const USER_SERVICE_PACKAGE_NAME = "user_service";

export interface UserServiceClient {
  createUser(request: CreateUserDto): Observable<User>;

  signIn(request: SignInDto): Observable<SignInResponse>;
}

export interface UserServiceController {
  createUser(request: CreateUserDto): Promise<User> | Observable<User> | User;

  signIn(request: SignInDto): Promise<SignInResponse> | Observable<SignInResponse> | SignInResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createUser", "signIn"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
